- name: Copy {{domain}}
  template:
    src: 'nginx.conf'
    dest: /etc/nginx/sites-available/{{domain}}

- name: Activate the {{domain}} site
  file: 
    src: /etc/nginx/sites-available/{{domain}}
    dest: /etc/nginx/sites-enabled/{{domain}}
    state: link

# - name: Restart nginx.service
#   systemd:
#     state: restarted
#     name: nginx