- name: Clone template project repository
  git:
    repo: "https://github.com/Ahmed-mzn/template-one"
    dest: "/home/khaled/pages/{{template}}/{{domain}}"
    version: main

- name: Create .env file
  template:
    src: '.env'
    dest: "/home/khaled/pages/{{template}}/{{domain}}"

- name: install node.js packages
  npm:
    path: "/home/khaled/pages/{{template}}/{{domain}}"

- name: Build app
  command: npm run build
  args:
    chdir: "/home/khaled/pages/{{template}}/{{domain}}"